version: "3.10"

services:
  app:
    build:
      context: .
    restart: always
    environment:
      - DB_HOST= www.iskit.pro
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - SQLSERVER_DB=${DB_NAME}
      - SQLSERVER_USER=${DB_USER}
      - PSQLSERVER_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000

volumes:
  mssql-data:
  static-data:
