# Generated by Django 4.2.7 on 2023-11-19 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(db_column='StudentID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='StudentName', max_length=255)),
                ('id_number', models.CharField(blank=True, db_column='IDnum', max_length=10, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', max_length=6, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='PhoneNumber', max_length=30, null=True)),
                ('phone_number2', models.CharField(blank=True, db_column='PhoneNumber2', max_length=50, null=True)),
                ('fax_number', models.CharField(blank=True, db_column='FaxNumber', max_length=30, null=True)),
                ('mobile_number', models.CharField(blank=True, db_column='MobileNumber', max_length=30, null=True)),
                ('email_address', models.CharField(blank=True, db_column='EmailAddress', max_length=255, null=True)),
                ('join_date', models.DateTimeField(blank=True, db_column='Joindate', null=True)),
                ('birth_date', models.DateTimeField(blank=True, db_column='Bir_date', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', max_length=2048, null=True)),
                ('firm_name', models.CharField(blank=True, db_column='FirmName', max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='ContactPerson', max_length=50, null=True)),
                ('division', models.CharField(blank=True, db_column='Devision', max_length=50, null=True)),
                ('website', models.CharField(blank=True, db_column='website', max_length=50, null=True)),
                ('credit_card', models.CharField(blank=True, db_column='CreditCard', max_length=50, null=True)),
                ('maavar', models.BooleanField(db_column='maavar', default=False)),
                ('credit_card_owner', models.CharField(blank=True, db_column='CrditCardOwner', max_length=50, null=True)),
                ('credit_card_type', models.PositiveSmallIntegerField(blank=True, db_column='CrditCardType', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('valid', models.CharField(blank=True, db_column='Valid', max_length=5, null=True)),
                ('mehiron_number', models.PositiveSmallIntegerField(blank=True, db_column='MehironNumber', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('id_card_owner', models.CharField(blank=True, db_column='idCardOwner', max_length=10, null=True)),
                ('payment_terms', models.PositiveSmallIntegerField(blank=True, db_column='TnaiTashlum', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('discount_percentage', models.FloatField(blank=True, db_column='DiscountPR', null=True)),
                ('photo_path', models.CharField(blank=True, db_column='PhotoPath', max_length=50, null=True)),
                ('field_type_id', models.IntegerField(blank=True, db_column='fldTypeID', null=True)),
                ('bank', models.IntegerField(blank=True, db_column='Bank', null=True)),
                ('branch', models.IntegerField(blank=True, db_column='Branch', null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=50, null=True)),
                ('opening_balance', models.DecimalField(blank=True, db_column='OpeningBalance', decimal_places=2, max_digits=10, null=True)),
                ('opening_balance_date', models.DateTimeField(blank=True, db_column='OpeningBalancedate', null=True)),
                ('no_vat', models.BooleanField(db_column='NoVat', default=False)),
                ('seif_income', models.PositiveSmallIntegerField(blank=True, db_column='SeifIncome', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('lo_pail', models.BooleanField(db_column='LoPail', default=False)),
                ('cust_type', models.PositiveSmallIntegerField(blank=True, db_column='CustType', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('cvv', models.PositiveSmallIntegerField(blank=True, db_column='CVV', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
