# Generated by Django 4.2.7 on 2023-11-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(db_column='StudentID', primary_key=True, serialize=False),
        ),
    ]
